apiVersion: v2
name: comcast
version: 4.2.0
appVersion: 1.0.0
description: periodic comcast data usage checks and save the results to InfluxDB
keywords:
  - comcast
  - influxdb
  - xfinity
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/comcast
icon: https://i.imgur.com/iR1dUpp.png
sources:
  - https://github.com/billimek/comcastUsage-for-influxdb
  - https://github.com/k8s-at-home/charts
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://billtomturner.github.io/library-charts/
    version: 3.0.0
