apiVersion: v2
appVersion: v4.11
description: Traccar is an open source GPS tracking system.
name: traccar
version: 4.5.0
kubeVersion: ">=1.16.0-0"
keywords:
- traccar
- gps
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/traccar
icon: "https://github.com/traccar/traccar-web/raw/master/web/icon.png"
sources:
- https://github.com/traccar/traccar
- https://hub.docker.com/r/traccar/traccar
maintainers:
- name: billimek
  email: jeff@billimek.com
dependencies:
- name: common
  repository: https://billtomturner.github.io/library-charts/
  version: 3.0.0
- name: mariadb
  version: 9.3.13
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
