apiVersion: v2
appVersion: 1.17.0
description: Open Source Continuous File Synchronization
name: syncthing
version: 1.4.0
kubeVersion: ">=1.16.0-0"
keywords:
- syncthing
- file sync
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/syncthing
icon: https://github.com/syncthing/syncthing/raw/main/assets/logo-128.png
sources:
- https://syncthing.net/
- https://github.com/syncthing/syncthing
maintainers:
- name: FlipEnergy
  email: dennis.zhang.nrg@gmail.com
- name: claughinghouse
dependencies:
- name: common
  repository: https://billtomturner.github.io/library-charts/
  version: 3.0.0
