apiVersion: v2
appVersion: 2.6.2
description: A self-hosted and PHP-based URL shortener application with CLI and REST interfaces
name: shlink
version: 1.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - shlink
  - url-shortener
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/shlink
icon: https://avatars.githubusercontent.com/u/20341790?s=200&v=4
sources:
  - https://github.com/shlinkio/shlink
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
dependencies:
  - name: common
    repository: https://billtomturner.github.io/library-charts/
    version: 3.0.0
  - name: postgresql
    version: 10.4.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 9.3.13
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
