#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/ubooquity
  pullPolicy: IfNotPresent
  tag: version-2.1.2

strategy:
  type: Recreate

env: {}
  # TZ: UTC

service:
  port:
    port: 2202
  additionalPorts:
    - port: 2203
      name: admin
      protocol: TCP

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir:
      enabled: false

  media:
    enabled: false
    emptyDir:
      enabled: false
    mountPath: /media
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""
